Repository asreview/asreview, pull requests merged in 2020-09, with the labels that each got.

#333 Add txt to import options for RIS
  docs/source/datasets.rst
Labels: documentation

#335 Update paths.py
  asreview/webapp/utils/paths.py
Labels: bug

#278 #277 two dockers
  README.md
  docker/README.md
  docker/asreview-cli/Dockerfile
  docker/asreview-lab/Dockerfile
  docs/source/installation.rst
Labels: enhancement

#318 Add a quick tour for new users
  asreview/webapp/package-lock.json
  asreview/webapp/package.json
  asreview/webapp/src/Components/QuickTourDialog.js
  asreview/webapp/src/Components/index.js
  asreview/webapp/src/Projects.js
  asreview/webapp/src/images/QuickTour/1_Welcome.svg
  asreview/webapp/src/images/QuickTour/2_SetUp.svg
  asreview/webapp/src/images/QuickTour/3_StartReviewing.svg
  asreview/webapp/src/images/QuickTour/4_BenefitFromAIAssisted.svg
  asreview/webapp/src/images/QuickTour/5_DontStress.svg
  asreview/webapp/src/images/QuickTour/6_DoneItsYourChoice.svg
  asreview/webapp/src/images/QuickTour/7_PublishYourWork.svg
Labels: enhancement, front-end

#338 Add an Alert for Exploration Mode
  asreview/webapp/src/Components/ArticlePanel.js
  asreview/webapp/src/Components/ReviewZone.js
  docs/source/user_testing_algorithms.rst
Labels: enhancement

#339 Add FAQ on ASReview LAB
  docs/source/faq.rst
Labels: documentation

#340 Improve performance of reading data
  asreview/webapp/api.py
  asreview/webapp/utils/io.py
Labels: enhancement
