Repository asreview/asreview, pull requests merged in 2020-07, with the labels that each got.

#300 Fix hyper parameter optimization for cluster qs
  asreview/query_strategies/cluster.py
Labels: bug

#303 Update installation with links to new step-by-step tutorial
  README.md
  docs/source/installation.rst
Labels: documentation

#298 Save dark mode and text size preferences in localStorage
  asreview/webapp/src/App.css
  asreview/webapp/src/App.js
  asreview/webapp/src/SettingsDialog.js
  asreview/webapp/src/SettingsHooks.js
Labels: enhancement

#292 Implementation of the undo feature
  CONTRIBUTORS.md
  asreview/webapp/api.py
  asreview/webapp/src/App.js
  asreview/webapp/src/Components/DecisionBar.js
  asreview/webapp/src/Components/DecisionUndoBar.js
  asreview/webapp/src/Components/ReviewZone.js
  asreview/webapp/src/SettingsDialog.js
  asreview/webapp/src/SettingsHooks.js
  asreview/webapp/src/globals.js
  asreview/webapp/utils/project.py
Labels: enhancement
