Repository asreview/asreview, pull requests merged in 2020-12, with the labels that each got.

#425 Output prior knowledge on CLI
  asreview/review/factory.py
Labels: enhancement

#427 info added about the ordering of the export file
  docs/source/features/post_screening.rst
Labels: documentation

#429 Add new option to select prior knowledge in simulation CLI
  asreview/entry_points/simulate.py
  asreview/review/factory.py
  asreview/review/simulate.py
  docs/source/API/cli.rst
  tests/state_files/test.h5
  tests/state_files/test.json
  tests/state_files/test_1_inst.h5
  tests/state_files/test_1_inst.json
  tests/test_simulate.py
Labels: enhancement

#431 Poorly defined record_ids now raise an error
  asreview/io/utils.py
  tests/test_asdata.py
Labels: enhancement

#428 add warning to upload clean data without duplicates or missing abstracts
  docs/source/features/pre_screening.rst
  docs/source/intro/datasets.rst
  docs/source/lab/oracle.rst
  docs/source/lab/simulation.rst
Labels: documentation

#432 Move data search to standalone module
  asreview/data.py
  asreview/search.py
  asreview/webapp/utils/datasets.py
  tests/test_data.py
Labels: enhancement

#420 Add reference to documentation and update text
  docs/source/intro/contribute.rst
Labels: documentation

#430 update text quicktour to match vocabular
  asreview/webapp/src/Components/QuickTourDialog.js
Labels: front-end

#433 Add FileNotFound error when datasets not found
  asreview/datasets.py
  tests/test_simulate.py
Labels: enhancement

#435 Typos
  DEVELOPMENT.md
  asreview/__main__.py
  docs/source/API/extensions_dev.rst
  docs/source/API/overview_cli.rst
Labels: documentation

#438 update hyperlinks to documentation in front-end
  asreview/webapp/src/Components/ReviewZone.js
  asreview/webapp/src/PreReviewComponents/ProjectAlgorithms.js
  asreview/webapp/src/PreReviewComponents/ProjectUpload.js
Labels: front-end

#440 Remove old pickle files when uploading new dataset
  asreview/webapp/utils/project.py
Labels: bug

#441 Resolve bug with flickering button when uploading partly labeled dataset
  asreview/webapp/src/PreReviewComponents/PreReviewZone.js
Labels: bug

#436 add info about record_id and clarified description of other meta-data
  docs/source/_static/css/asreviewtheme.css
  docs/source/intro/datasets.rst
Labels: documentation

#444 Replace tablet screenshot by browser screenshot to avoid confusion
  README.md
  images/ASReviewWebApp.png
Labels: documentation

#447 Add function for backwards compat of covid19 plugin
  asreview/datasets.py
Labels: bug
