Repository asreview/asreview, pull requests merged in 2020-10, with the labels that each got.

#353 Update help text for prior_idx in simulate.py
  asreview/entry_points/simulate.py
Labels: documentation

#346 Fix docstrings and documentation for asreview classifiers
  .github/workflows/ci-core.yml
  asreview/balance_strategies/base.py
  asreview/balance_strategies/double.py
  asreview/balance_strategies/triple.py
  asreview/balance_strategies/undersample.py
  asreview/feature_extraction/__init__.py
  asreview/feature_extraction/doc2vec.py
  asreview/feature_extraction/embedding_idf.py
  asreview/feature_extraction/embedding_lstm.py
  asreview/feature_extraction/sbert.py
  asreview/feature_extraction/tfidf.py
  asreview/models/__init__.py
  asreview/models/base.py
  asreview/models/logistic.py
  asreview/models/lstm_base.py
  asreview/models/lstm_pool.py
  asreview/models/nb.py
  asreview/models/nn_2_layer.py
  asreview/models/rf.py
  asreview/models/svm.py
  asreview/query_strategies/base.py
  asreview/query_strategies/cluster.py
  asreview/query_strategies/max.py
  asreview/query_strategies/mixed.py
  asreview/query_strategies/random.py
  asreview/query_strategies/uncertainty.py
  asreview/query_strategies/utils.py
  asreview/review/base.py
  asreview/review/factory.py
  asreview/review/simulate.py
  docs/source/api.rst
  docs/source/conf.py
  docs/source/models.rst
  docs/source/reference.rst
  tests/test_feature.py
  tests/test_simulate.py
Labels: documentation

#347 Add python linter (flake8)
  .github/workflows/ci-core.yml
  asreview/__main__.py
  asreview/analysis/analysis.py
  asreview/analysis/statistics.py
  asreview/config.py
  asreview/data.py
  asreview/datasets.py
  asreview/io/paper_record.py
  asreview/query_strategies/cluster.py
  asreview/query_strategies/mixed.py
  asreview/review/base.py
  asreview/review/factory.py
  asreview/review/minimal.py
  asreview/review/simulate.py
  asreview/settings.py
  asreview/state/base.py
  asreview/state/dict.py
  asreview/state/hdf5.py
  asreview/state/json.py
  asreview/state/utils.py
  asreview/utils.py
  asreview/webapp/utils/__init__.py
  setup.cfg
  setup.py
Labels: CI

#354 Some clarification in the `-h` documentation.
  asreview/entry_points/base.py
Labels: documentation

#363 Fix slicing
  asreview/data.py
  asreview/review/simulate.py
  tests/demo_data/generic_partial_labels.csv
  tests/state_files/test_1_inst.h5
  tests/state_files/test_1_inst.json
  tests/test_simulate.py
Labels: bug

#364 Print warning if record ids are not unique.
  asreview/io/utils.py
  tests/demo_data/generic_bad_record_id.csv
  tests/test_data.py
Labels: bug, enhancement

#366 Replace oracle entry point by lab entry point
  DEVELOPMENT.md
  asreview/__main__.py
  asreview/entry_points/__init__.py
  asreview/entry_points/batch.py
  asreview/entry_points/gui.py
  asreview/utils.py
  asreview/webapp/start_flask.py
  docker/asreview-lab/Dockerfile
  docs/source/covid-19.rst
  docs/source/installation.rst
  docs/source/quicktour.rst
  setup.py
  tests/test_simulate.py
Labels: documentation, enhancement, front-end

#370 Fix reference to outdated option in simulate command line
  asreview/entry_points/simulate.py
Labels: documentation

#371 Move content models page to docstrings
  asreview/balance_strategies/__init__.py
  asreview/balance_strategies/simple.py
  asreview/balance_strategies/triple.py
  asreview/balance_strategies/undersample.py
  asreview/feature_extraction/__init__.py
  asreview/feature_extraction/doc2vec.py
  asreview/feature_extraction/embedding_idf.py
  asreview/feature_extraction/embedding_lstm.py
  asreview/feature_extraction/sbert.py
  asreview/feature_extraction/tfidf.py
  asreview/models/__init__.py
  asreview/models/lstm_base.py
  asreview/models/lstm_pool.py
  asreview/models/nb.py
  asreview/models/nn_2_layer.py
  asreview/query_strategies/__init__.py
  asreview/query_strategies/cluster.py
  asreview/query_strategies/max.py
  asreview/query_strategies/mixed.py
  asreview/query_strategies/random.py
  asreview/query_strategies/uncertainty.py
  docs/source/index.rst
  docs/source/models.rst
Labels: documentation

#373 Reorganize the documentation index
  docs/source/index.rst
  docs/source/quicktour.rst
  docs/source/sim_overview.rst
Labels: documentation

#375 Subcommand to output available algorithms
  asreview/entry_points/__init__.py
  asreview/entry_points/algorithms.py
  docs/source/cli.rst
  docs/source/extensions_dev.rst
  setup.py
Labels: enhancement

#372 Join and rewrite documentation on extensions
  docs/source/extensions.rst
  docs/source/extensions_dev.rst
  docs/source/index.rst
Labels: documentation

#350 Replace RISParser by rispy
  asreview/config.py
  asreview/io/ris_reader.py
  setup.py
Labels: bug, enhancement

#380 Update quicktour.rst
  docs/source/quicktour.rst
Labels: documentation

#309 Add stop words to TFIDF
  asreview/feature_extraction/tfidf.py
Labels: enhancement

#385 Add option to remove temporary files from project
  asreview/entry_points/lab.py
  asreview/webapp/start_flask.py
  asreview/webapp/utils/project.py
  docs/source/cli.rst
  docs/source/index.rst
  docs/source/troubleshooting.rst
Labels: enhancement

#390 Basic tests for flask application
  .github/workflows/ci-core.yml
  .github/workflows/ci-frontend.yml
  asreview/webapp/tests/conftest.py
  asreview/webapp/tests/test_api.py
  asreview/webapp/tests/test_webapp.py
Labels: CI

#389 Don't fail on repeated project imports
  asreview/webapp/api.py
Labels: enhancement

#379 Replace column definitions into more flexible structure
  asreview/config.py
  asreview/data.py
  asreview/io/excel_reader.py
  asreview/io/paper_record.py
  asreview/io/ris_reader.py
  asreview/io/utils.py
  asreview/webapp/api.py
  asreview/webapp/utils/io.py
  tests/test_readers.py
Labels: enhancement
