Repository asreview/asreview, pull requests merged in 2020-11, with the labels that each got.

#396 Improve review screen html structure
  asreview/webapp/src/Components/ArticlePanel.js
  asreview/webapp/src/Components/DecisionBar.js
  asreview/webapp/src/Components/Header.js
  asreview/webapp/src/Components/ReviewZone.js
Labels: front-end

#393 update info metadata
  docs/source/datasets.rst
Labels: documentation

#399 Fix broken links and use sphinx syntax for cross-refs
  docs/source/covid-19.rst
  docs/source/datasets.rst
  docs/source/faq.rst
  docs/source/installation.rst
  docs/source/quicktour.rst
  docs/source/sim_overview.rst
  docs/source/simulation_study_results.rst
  docs/source/user_testing_algorithms.rst
Labels: documentation

#401 Nan values should be converted to empty strings
  asreview/io/utils.py
Labels: bug

#369 Implemented basic simulation flow
  asreview/webapp/api.py
  asreview/webapp/run_model.py
  asreview/webapp/src/PreReviewComponents/LabeledItems.js
  asreview/webapp/src/PreReviewComponents/PreReviewZone.js
  asreview/webapp/src/PreReviewComponents/PriorKnowledge.js
  asreview/webapp/src/PreReviewComponents/ProjectInit.js
  asreview/webapp/src/PreReviewComponents/ProjectPage.js
  asreview/webapp/src/PreReviewComponents/ProjectPageOracle.js
  asreview/webapp/src/PreReviewComponents/ProjectPageSimulation.js
  asreview/webapp/src/PreReviewComponents/ProjectUpload.js
  asreview/webapp/src/PreReviewComponents/StartSimulation.js
  asreview/webapp/src/PreReviewComponents/index.js
  asreview/webapp/src/ProjectCard.js
  asreview/webapp/src/Projects.js
  asreview/webapp/src/PublicationZone.js
  asreview/webapp/src/StatisticsZone.js
  asreview/webapp/src/api/ProjectAPI.js
  asreview/webapp/src/api/index.js
  asreview/webapp/src/globals.js
  asreview/webapp/utils/io.py
  asreview/webapp/utils/paths.py
  asreview/webapp/utils/project.py
  package-lock.json
Labels: enhancement

#402 Sort projects on datetime created
  asreview/webapp/api.py
  asreview/webapp/utils/project.py
Labels: enhancement, front-end

#403 Make project card fully clickable
  asreview/webapp/src/ProjectCard.js
Labels: enhancement, front-end

#405 change name max sampling
  asreview/webapp/src/PreReviewComponents/ProjectAlgorithms.js
Labels: front-end, good first issue

#419 Update intro text with link to license, research team and Github
  docs/source/index.rst
Labels: documentation

#421 Fix error in error catch on run_model entry point
  asreview/webapp/run_model.py
Labels: bug

#422 Refactor get statistics in webapp
  asreview/webapp/utils/project.py
Labels: enhancement

#392 Add option to read state file from ASReview project file
  asreview/state/__init__.py
  asreview/state/utils.py
  tests/state_files/test_1_inst.asreview
  tests/test_state.py
Labels: enhancement
