Repository asreview/asreview, pull requests merged in 2021-06, with the labels that each got.

#631 Add doi to Configuration File
  asreview/config.py
  asreview/data/base.py
  asreview/io/paper_record.py
  asreview/webapp/utils/project.py
Labels: bug, enhancement

#632 Improve documentation
  README.md
  docs/source/features/pre_screening.rst
  docs/source/features/screening.rst
  docs/source/guides/activelearning.rst
  docs/source/guides/sim_overview.rst
  docs/source/lab/exploration.rst
  docs/source/lab/oracle.rst
  docs/source/plugins/covid19.rst
  docs/source/plugins/overview_plugins.rst
Labels: documentation

#584 Edit project info after creating a new project
  asreview/webapp/api.py
  asreview/webapp/src/PreReviewComponents/ProjectInfo.js
  asreview/webapp/src/PreReviewComponents/ProjectPage.js
  asreview/webapp/src/PreReviewComponents/ProjectUpload.js
  asreview/webapp/src/PreReviewComponents/index.js
  asreview/webapp/src/Projects.js
  asreview/webapp/src/StatisticsZone.js
  asreview/webapp/src/api/ProjectAPI.js
  asreview/webapp/tests/test_api.py
  asreview/webapp/utils/project.py
Labels: enhancement

#605 Add min stopping simulation option
  asreview/entry_points/simulate.py
  asreview/review/base.py
  asreview/settings.py
  asreview/types.py
  docs/source/API/cli.rst
  tests/test_simulate.py
Labels: enhancement
