Repository asreview/asreview, pull requests merged in 2021-03, with the labels that each got.

#484 add vocabulary to documentation
  docs/source/index.rst
  docs/source/intro/vocabulary.rst
Labels: documentation

#474 Add WSGI server with gevent and create check for ports already in use
  asreview/entry_points/lab.py
  asreview/webapp/start_flask.py
  asreview/webapp/utils/misc.py
  docs/source/API/cli.rst
  setup.py
Labels: enhancement

#510 Refactor ASReview settings submodule
  asreview/settings.py
Labels: enhancement

#535 Fix toctree wordcloud
  docs/source/index.rst
Labels: documentation

#532 Add project mode to datasets panel
  asreview/webapp/src/PreReviewComponents/PreReviewZone.js
  asreview/webapp/src/PreReviewComponents/ProjectPage.js
  asreview/webapp/src/PreReviewComponents/ProjectUpload.js
Labels: enhancement

#534 Add REST API test for project generation and adding dataset
  asreview/webapp/tests/test_api.py
Labels: CI
