Repository asreview/asreview, pull requests merged in 2021-12, with the labels that each got.

#855 Refactor updating project info
  asreview/webapp/api.py
  asreview/webapp/utils/project.py
Labels: enhancement

#866 Fix adding extension dataset when setting up a project
  asreview/webapp/src/PreReviewComponents/PluginDataset.js
  asreview/webapp/src/PreReviewComponents/ProjectUploadPluginDatasets.js
Labels: bug

#880 Raise more informative error on dataset without titles
  asreview/search.py
  asreview/webapp/api.py
Labels: documentation, front-end

#884 add ris to documentation on exporting data
  docs/source/features/post_screening.rst
Labels: documentation

#887 Exclude labeled items from search
  asreview/webapp/api.py
Labels: enhancement, front-end

#897 Fix regex not supported by Safari
  asreview/webapp/src/ProjectComponents/AnalyticsComponents/ProgressChart.js
Labels: bug, front-end
