Repository asreview/asreview, pull requests merged in 2021-01, with the labels that each got.

#446 Benchmark platform integration
  asreview/datasets.py
  setup.py
  tests/test_data.py
Labels: enhancement

#406 Add Review History Dialog
  asreview/webapp/src/App.js
  asreview/webapp/src/Components/Header.js
  asreview/webapp/src/Components/HistoryDialog.js
  asreview/webapp/src/Components/HistoryListCard.js
  asreview/webapp/src/Components/ReviewZone.js
  asreview/webapp/src/Components/index.js
Labels: enhancement, front-end

#452 improve text dataset requirements
  docs/source/intro/datasets.rst
Labels: documentation

#448 Add benchmark datasets to LAB
  asreview/datasets.py
  asreview/webapp/api.py
  asreview/webapp/src/PreReviewComponents/ProjectUpload.js
  asreview/webapp/src/PreReviewComponents/ProjectUploadBenchmarkDatasets.js
  asreview/webapp/src/PreReviewComponents/ProjectUploadDataset.js
  asreview/webapp/src/PreReviewComponents/ProjectUploadDatasets.js
  asreview/webapp/src/PreReviewComponents/ProjectUploadPluginDatasets.js
  asreview/webapp/src/PreReviewComponents/index.js
  asreview/webapp/utils/datasets.py
Labels: enhancement, front-end

#466 Add documentation on plotting ASReview files
  docs/source/plugins/plugin_visualization.rst
Labels: documentation

#459 added a brief introduction to the new About page
  docs/source/intro/about.rst
Labels: documentation

#462 title pop-up history overview
  asreview/webapp/src/Components/HistoryDialog.js
Labels: front-end

#463 Access history dialog only in review state
  asreview/webapp/src/App.js
  asreview/webapp/src/Components/HistoryDialog.js
  asreview/webapp/src/Components/HistoryListCard.js
  asreview/webapp/src/Components/ReviewZone.js
Labels: bug

#461 add documentation on history panel
  docs/images/asreview_screening_history_metadata.png
  docs/images/asreview_screening_history_overview.png
  docs/source/features/screening.rst
Labels: documentation

#458 added information how to remove ASReview
  docs/source/intro/installation.rst
Labels: documentation

#439 improve text for searching prior knowledge
  asreview/webapp/src/PreReviewComponents/ListItemPaper.js
  asreview/webapp/src/PreReviewComponents/PriorKnowledgeRandom.js
  asreview/webapp/src/PreReviewComponents/PriorKnowledgeSearch.js
Labels: front-end

#453 improve test compatibility and added error in Distillor
  docs/source/intro/datasets.rst
Labels: documentation

#468 Add documentation on benchmark datasets
  asreview/entry_points/simulate.py
  asreview/review/factory.py
  asreview/webapp/src/PreReviewComponents/ProjectUpload.js
  docs/images/gifs/virusM_recall_slow_1trial_fancy.gif
  docs/source/API/cli.rst
  docs/source/features/pre_screening.rst
  docs/source/guides/simulation_study_results.rst
  docs/source/intro/datasets.rst
  docs/source/intro/faq.rst
  docs/source/lab/exploration.rst
  docs/source/lab/oracle.rst
Labels: documentation

#471 Avoid file changes after running tests
  tests/test_simulate.py
  tests/test_state.py
Labels: CI

#475 Remove whitespace from column names
  asreview/io/utils.py
  tests/demo_data/generic_column_names_with_spaces.csv
  tests/test_asdata.py
Labels: bug, enhancement
