Repository asreview/asreview, pull requests merged in 2021-08, with the labels that each got.

#663 Add Help Dialog
  asreview/webapp/src/App.js
  asreview/webapp/src/Components/Header.js
  asreview/webapp/src/Components/MenuDrawer.js
  asreview/webapp/src/HelpDialog.js
  asreview/webapp/src/api/UtilsAPI.js
  asreview/webapp/src/api/index.js
Labels: enhancement, front-end

#664 Add one-click-deploy buttons
  DEVELOPMENT.md
  app.json
  azuredeploy.json
  azuredeploy.parameters.json
Labels: enhancement

#624 New ASReview Homepage
  asreview/webapp/src/ProjectStatusGraphic.js
  asreview/webapp/src/ProjectTable.js
  asreview/webapp/src/Projects.js
  asreview/webapp/src/globals.js
  asreview/webapp/utils/project.py
Labels: front-end

#675 Redesign Review Screen
  asreview/webapp/package-lock.json
  asreview/webapp/package.json
  asreview/webapp/src/App.js
  asreview/webapp/src/Components/ArticlePanel.js
  asreview/webapp/src/Components/DecisionBar.js
  asreview/webapp/src/Components/DecisionFeedback.js
  asreview/webapp/src/Components/Header.js
  asreview/webapp/src/Components/ReviewDrawer.js
  asreview/webapp/src/Components/index.js
  asreview/webapp/src/InReviewComponents/DecisionButton.js
  asreview/webapp/src/InReviewComponents/DecisionUndoBar.js
  asreview/webapp/src/InReviewComponents/ExplorationModeBanner.js
  asreview/webapp/src/InReviewComponents/RecordCard.js
  asreview/webapp/src/InReviewComponents/ReviewDialog.js
  asreview/webapp/src/InReviewComponents/StatsSheet.js
  asreview/webapp/src/InReviewComponents/index.js
  asreview/webapp/src/PreReviewComponents/ProjectPage.js
  asreview/webapp/src/SideStats/ProgressPanel.js
  asreview/webapp/src/SideStats/ProjectPanel.js
  asreview/webapp/src/constants/action-types.js
  asreview/webapp/src/globals.js
  asreview/webapp/src/hooks/SettingsHooks.js
  asreview/webapp/src/redux/actions/index.js
  asreview/webapp/src/redux/reducers/index.js
Labels: enhancement, front-end

#687 Add Note Sheet to Review Dialog
  asreview/webapp/src/InReviewComponents/NoteSheet.js
  asreview/webapp/src/InReviewComponents/RecordCard.js
  asreview/webapp/src/InReviewComponents/ReviewDialog.js
  asreview/webapp/src/InReviewComponents/index.js
Labels: enhancement, front-end
