Repository asreview/asreview, pull requests merged in 2022-07, with the labels that each got.

#1177 Simplify steps to add dataset
  asreview/webapp/src/Components/AppBarWithinDialog.js
  asreview/webapp/src/ProjectComponents/ImportFromFile.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/AddDataset.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/DatasetFromURL.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/EntryPointDataset.js
  asreview/webapp/src/ProjectComponents/SetupComponents/SetupDialog.js
  docs/images/setup_add_dataset.png
  docs/images/setup_datasets_simulate_benchmark.png
Labels: front-end

#1176 Display DOI/URL of labeled records on History page
  asreview/webapp/api.py
  asreview/webapp/src/App.css
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecordCard.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/RecordCard.js
  docs/images/project_history.png
Labels: enhancement, front-end

#1182 Fix broken rendering of API reference on RTD
  docs/requirements.txt
  docs/source/_templates/autosummary/class.rst
  docs/source/_templates/custom-class-template.rst
  docs/source/_templates/custom-module-template.rst
  docs/source/conf.py
  docs/source/reference.rst
Labels: documentation
