Repository asreview/asreview, pull requests merged in 2022-01, with the labels that each got.

#906 Adjust documentation on batch simulations
  asreview/entry_points/simulate.py
  docs/source/API/cli.rst
Labels: documentation

#913 Extend get_labels with option to exclude priors
  asreview/state/sqlstate.py
  tests/test_state.py
Labels: enhancement

#914 Add option to exclude priors from charts (excluded by default)
  asreview/webapp/api.py
Labels: front-end

#922 Extend debug_label on prior REST calls in Exploration mode
  asreview/webapp/api.py
Labels: front-end

#926 Add alert to record card of prior selection in exploration mode
  asreview/webapp/src/ProjectComponents/ReviewComponents/RecordCard.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/PriorUnlabeled.js
  asreview/webapp/src/StyledComponents/StyledAlert.js
Labels: enhancement, front-end

#927 Style project delete dialog
  asreview/webapp/src/Components/ProjectDeleteDialog.js
Labels: front-end

#932 Style project page header and content
  asreview/webapp/src/App.css
  asreview/webapp/src/Components/PageHeader.js
  asreview/webapp/src/Components/SnackbarErrorHandler.js
  asreview/webapp/src/Components/index.js
  asreview/webapp/src/ProjectComponents/AnalyticsComponents/AnalyticsPage.js
  asreview/webapp/src/ProjectComponents/AnalyticsComponents/NumberCard.js
  asreview/webapp/src/ProjectComponents/AnalyticsComponents/ProgressChart.js
  asreview/webapp/src/ProjectComponents/AnalyticsComponents/ProgressDensityChart.js
  asreview/webapp/src/ProjectComponents/AnalyticsComponents/ProgressRecallChart.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/DataForm.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/DataFormCard.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/DetailsPage.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/InfoForm.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/ModelForm.js
  asreview/webapp/src/ProjectComponents/ExportComponents/ExportPage.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/HistoryPage.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecord.js
  asreview/webapp/src/ProjectComponents/ProjectPage.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/DecisionButton.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/ExplorationModeBanner.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/RecordCard.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/ReviewPage.css
  asreview/webapp/src/ProjectComponents/ReviewComponents/ReviewPage.js
  asreview/webapp/src/StyledComponents/StyledTypography.js
  asreview/webapp/src/globals.js
Labels: front-end

#925 Extend REST API with option to add and update notes
  asreview/state/sqlstate.py
  asreview/webapp/api.py
  asreview/webapp/utils/project.py
  tests/test_state.py
Labels: help wanted, front-end

#937 Interface for adding/editing/viewing record note
  asreview/webapp/api.py
  asreview/webapp/src/App.css
  asreview/webapp/src/ProjectComponents/HistoryComponents/Filter.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/HistoryPage.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabelChip.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecord.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecordCard.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/RecordCardNote.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/index.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/DecisionButton.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/DecisionUndoBar.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/NoteSheet.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/RecordCard.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/ReviewPage.css
  asreview/webapp/src/ProjectComponents/ReviewComponents/ReviewPage.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/PriorUnlabeled.js
  asreview/webapp/src/api/ProjectAPI.js
  asreview/webapp/src/images/ElasAvatar.svg
Labels: enhancement, front-end

#938 Fix get statistics of number since last relevant
  asreview/webapp/utils/project.py
Labels: bug

#939 Fix issues with project setup dialog
  asreview/webapp/src/HomeComponents/DashboardComponents/DashboardPage.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/DataForm.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/DetailsPage.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/InfoForm.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/index.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecord.js
  asreview/webapp/src/ProjectComponents/ProjectInfoForm.js
  asreview/webapp/src/ProjectComponents/ProjectModeSelect.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/AddDataset.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/AddPriorKnowledge.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/DataForm.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/PriorLabeled.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DetailsComponents/DetailsForm.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DetailsComponents/index.js
  asreview/webapp/src/ProjectComponents/SetupComponents/ModelComponents/ModelForm.js
  asreview/webapp/src/ProjectComponents/SetupComponents/SetupDialog.js
  asreview/webapp/src/ProjectComponents/index.js
Labels: front-end

#935 Add project check dialog
  asreview/state/sql_converter.py
  asreview/webapp/api.py
  asreview/webapp/src/HomeComponents/DashboardComponents/ProjectCheckDialog.js
  asreview/webapp/src/HomeComponents/DashboardComponents/ProjectTable.js
  asreview/webapp/src/HomeComponents/DashboardComponents/TableRowButton.js
  asreview/webapp/src/HomeComponents/DashboardComponents/index.js
  asreview/webapp/src/api/ProjectAPI.js
  asreview/webapp/tests/test_api.py
  asreview/webapp/tests/test_project.py
Labels: enhancement, front-end

#941 Add prior knowledge option to project history filter
  asreview/webapp/api.py
  asreview/webapp/src/ProjectComponents/DetailsComponents/DataForm.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/DataFormCard.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/DetailsPage.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/Filter.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/HistoryPage.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecord.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecordCard.js
  asreview/webapp/src/ProjectComponents/ProjectPage.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/PriorLabeled.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/PriorUnlabeled.js
  asreview/webapp/src/globals.js
Labels: enhancement, front-end

#898 Change folder structure for legacy files and change record_ids in converter
  asreview/io/utils.py
  asreview/review/base.py
  asreview/state/base.py
  asreview/state/sql_converter.py
  asreview/state/sqlstate.py
  asreview/webapp/api.py
  asreview/webapp/tests/test_project.py
  tests/asreview_files/test_state_example_converted.asreview/legacy/data/ADHD.csv
  tests/asreview_files/test_state_example_converted.asreview/legacy/kwargs.json
  tests/asreview_files/test_state_example_converted.asreview/legacy/labeled.json
  tests/asreview_files/test_state_example_converted.asreview/legacy/lock.sqlite
  tests/asreview_files/test_state_example_converted.asreview/legacy/pool.json
  tests/asreview_files/test_state_example_converted.asreview/legacy/proba.csv
  tests/asreview_files/test_state_example_converted.asreview/legacy/project.json
  tests/asreview_files/test_state_example_converted.asreview/legacy/result.json
  tests/asreview_files/test_state_example_converted.asreview/project.json
  tests/asreview_files/test_state_example_converted.asreview/reviews/00fb4eaa92864667a022bca340348045/results.sql
  tests/asreview_files/test_state_example_converted.asreview/reviews/00fb4eaa92864667a022bca340348045/settings_metadata.json
  tests/asreview_files/test_state_example_converted.asreview/reviews/735ef9e2ca654425b6cebd89dfed2498/results.sql
  tests/asreview_files/test_state_example_converted.asreview/reviews/735ef9e2ca654425b6cebd89dfed2498/settings_metadata.json
  tests/asreview_files/test_state_example_with_times.asreview/legacy/data/cohen_no_labels.csv
  tests/asreview_files/test_state_example_with_times.asreview/legacy/data/cohen_no_labels.csv.pickle
  tests/asreview_files/test_state_example_with_times.asreview/legacy/labeled.json
  tests/asreview_files/test_state_example_with_times.asreview/legacy/lock.sqlite
  tests/asreview_files/test_state_example_with_times.asreview/legacy/pool.json
  tests/asreview_files/test_state_example_with_times.asreview/legacy/project.json
  tests/test_converter.py
  tests/test_simulate.py
  tests/test_state.py
Labels: enhancement

#936 Added xref2csv reference
  docs/source/extensions/overview_extensions.rst
Labels: documentation

#949 Fix invalid date in Safari
  asreview/webapp/src/HomeComponents/DashboardComponents/ProjectTable.js
Labels: bug, Discussion

#948 Fix labeled_stats
  asreview/webapp/api.py
Labels: bug
