Repository asreview/asreview, pull requests merged in 2022-05, with the labels that each got.

#1044 Add maintainer to readme
  README.md
Labels: documentation

#1058 Add balance strategy select option
  asreview/webapp/api.py
  asreview/webapp/src/ProjectComponents/DetailsComponents/ModelForm.js
  asreview/webapp/src/ProjectComponents/SetupComponents/ModelComponents/ModelForm.js
  asreview/webapp/src/ProjectComponents/SetupComponents/SetupDialog.js
  asreview/webapp/src/api/ProjectAPI.js
Labels: enhancement, front-end

#1057 Add button to delete prior knowledge when creating new project
  asreview/webapp/api.py
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecord.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecordCard.js
Labels: front-end

#1059 Resolve failing github action on excel export
  asreview/project.py
  asreview/state/paths.py
  setup.py
Labels: bug, CI

#1088 Fix documentation errors in sphinx
  docs/source/API/overview_development.rst
  docs/source/API/reference.rst
  docs/source/intro/datasets.rst
Labels: documentation

#1085 Update API example
  docs/source/guides/api.rst
Labels: documentation

#1091 Fix min simulate option and make it default
  asreview/entry_points/simulate.py
  asreview/review/base.py
  asreview/review/simulate.py
  asreview/state/sqlstate.py
  asreview/types.py
  tests/test_simulate.py
Labels: enhancement

#1100 Fix issue with RIS exporter for A2-A3-A4 fields
  asreview/io/ris_writer.py
  tests/demo_data/ris_issue_1099.txt
  tests/test_writers.py
Labels: bug

#1096 Change radius of note field
  asreview/webapp/src/ProjectComponents/ReviewComponents/NoteSheet.js
Labels: front-end
