Repository asreview/asreview, pull requests merged in 2022-03, with the labels that each got.

#970 Add ML FE to documentation
  docs/source/extensions/overview_extensions.rst
Labels: documentation

#1004 Adjust interface for the simulation project
  asreview/entry_points/simulate.py
  asreview/webapp/api.py
  asreview/webapp/src/Components/DrawerItemContainer.js
  asreview/webapp/src/HomeComponents/DashboardComponents/ProjectTable.js
  asreview/webapp/src/HomeComponents/DashboardComponents/TableRowButton.js
  asreview/webapp/src/ProjectComponents/AnalyticsComponents/AnalyticsPage.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/DetailsPage.js
  asreview/webapp/src/ProjectComponents/ExportComponents/ExportPage.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/HistoryPage.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecord.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecordCard.js
  asreview/webapp/src/ProjectComponents/ProjectPage.js
  asreview/webapp/src/ProjectComponents/SetupComponents/FinishSetup.js
  asreview/webapp/src/ProjectComponents/SetupComponents/SetupDialog.js
  asreview/webapp/src/api/ProjectAPI.js
  asreview/webapp/src/globals.js
Labels: enhancement, front-end

#1006 Adjust interface of settings and help dialog
  asreview/webapp/src/App.css
  asreview/webapp/src/Components/HelpDialog.js
  asreview/webapp/src/Components/SettingsDialog.js
  asreview/webapp/src/ProjectComponents/ProjectImportDialog.js
  asreview/webapp/src/ProjectComponents/SetupComponents/SetupDialog.js
  asreview/webapp/src/api/UtilsAPI.js
Labels: front-end

#999 Introduce ProjectAPI
  asreview/__init__.py
  asreview/data/base.py
  asreview/datasets.py
  asreview/entry_points/simulate.py
  asreview/entry_points/state_inspect.py
  asreview/io/ris_writer.py
  asreview/project.py
  asreview/review/base.py
  asreview/review/simulate.py
  asreview/state/__init__.py
  asreview/state/paths.py
  asreview/state/sql_converter.py
  asreview/state/sqlstate.py
  asreview/state/utils.py
  asreview/utils.py
  asreview/webapp/api.py
  asreview/webapp/io.py
  asreview/webapp/run_model.py
  asreview/webapp/start_flask.py
  asreview/webapp/types.py
  asreview/webapp/utils/__init__.py
  asreview/webapp/utils/datasets.py
  asreview/webapp/utils/misc.py
  asreview/webapp/utils/project.py
  asreview/webapp/utils/project_path.py
  asreview/webapp/utils/validation.py
  tests/test_converter.py
  tests/test_data.py
  tests/test_init.py
  tests/test_simulate.py
  tests/test_state.py
Labels: enhancement

#1016 Resolve numpy deprecation warnings
  asreview/models/balance/triple.py
  asreview/state/legacy/base.py
  asreview/state/legacy/dict.py
  asreview/state/legacy/hdf5.py
  tests/test_balance.py
  tests/test_state.py
Labels: dependencies

#1011 Refactor status handling in ASReview backend
  asreview/entry_points/simulate.py
  asreview/project.py
  asreview/review/base.py
  asreview/state/sql_converter.py
  asreview/webapp/api.py
  asreview/webapp/run_model.py
  asreview/webapp/src/Components/DrawerItemContainer.js
  asreview/webapp/src/HomeComponents/DashboardComponents/DashboardPage.js
  asreview/webapp/src/HomeComponents/DashboardComponents/ProjectTable.js
  asreview/webapp/src/HomeComponents/DashboardComponents/TableRowButton.js
  asreview/webapp/src/ProjectComponents/AnalyticsComponents/ProgressRecallChart.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/DetailsPage.js
  asreview/webapp/src/ProjectComponents/ExportComponents/ExportPage.js
  asreview/webapp/src/ProjectComponents/ProjectPage.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/ReviewPageFinished.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/DataForm.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/DataFormCard.js
  asreview/webapp/src/ProjectComponents/SetupComponents/FinishSetup.js
  asreview/webapp/src/ProjectComponents/SetupComponents/SetupDialog.js
  asreview/webapp/src/api/ProjectAPI.js
  asreview/webapp/src/globals.js
  asreview/webapp/tests/test_api.py
  asreview/webapp/tests/test_project.py
  tests/test_simulate.py
Labels: enhancement

#1020 Lint for E401
  asreview/config.py
  asreview/data/base.py
  asreview/entry_points/lab.py
  asreview/entry_points/simulate.py
  asreview/io/ris_writer.py
  asreview/models/query/base.py
  asreview/models/query/utils.py
  asreview/project.py
  asreview/review/base.py
  asreview/state/utils.py
  asreview/webapp/api.py
  asreview/webapp/io.py
  asreview/webapp/run_model.py
  asreview/webapp/tests/test_api.py
  setup.cfg
  tests/test_init.py
  tests/test_readers.py
  tests/test_state.py
Labels: CI

#1021 Enable mode select during the project setup process
  asreview/webapp/src/HomeComponents/DashboardComponents/ProjectTable.js
  asreview/webapp/src/ProjectComponents/ProjectInfoForm.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/AddDataset.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/DataForm.js
  asreview/webapp/src/ProjectComponents/SetupComponents/SetupDialog.js
Labels: enhancement, front-end

#867 Remove VersionedBaseDataset and refacter datasets submodule
  asreview/data/base.py
  asreview/datasets.py
  asreview/webapp/api.py
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/AddDataset.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/DatasetFromBenchmark.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/DatasetFromEntryPoint.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/DatasetFromExtension.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/EntryPointDataset.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/ExtensionDataset.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/index.js
  docs/source/API/reference.rst
  setup.py
  tests/test_data.py
  tests/test_datasets.py
Labels: bug, enhancement
