Repository asreview/asreview, pull requests merged in 2022-06, with the labels that each got.

#1045 Replace individual authors on Zenodo with team name
  .zenodo.json
Labels: documentation

#1148 Fix bug with metadata not stored for feature matrix in oracle
  asreview/webapp/run_model.py
Labels: bug

#1164 Responsive project setup screen
  asreview/webapp/src/Components/AppBarWithinDialog.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/HistoryPage.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecord.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecordCard.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/AddDataset.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/AddPriorKnowledge.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/DataFormCard.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/DatasetFromEntryPoint.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/EntryPointDataset.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/PriorLabeled.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/PriorRandom.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/PriorSearch.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/PriorUnlabeled.js
  asreview/webapp/src/ProjectComponents/SetupComponents/FinishSetup.js
  asreview/webapp/src/ProjectComponents/SetupComponents/SetupDialog.js
Labels: front-end
