Repository asreview/asreview, pull requests merged in 2022-02, with the labels that each got.

#950 Update project import dialog
  asreview/webapp/api.py
  asreview/webapp/src/Components/ActionsFeedbackBar.js
  asreview/webapp/src/Components/ProjectImportDialog.js
  asreview/webapp/src/Components/index.js
  asreview/webapp/src/HomeComponents/DashboardComponents/DashboardPage.js
  asreview/webapp/src/ProjectComponents/ImportFromFile.js
  asreview/webapp/src/ProjectComponents/ProjectImportDialog.js
  asreview/webapp/src/ProjectComponents/SetupComponents/CloseSetupInfoBar.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/AddDataset.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/index.js
  asreview/webapp/src/ProjectComponents/SetupComponents/SetupDialog.js
  asreview/webapp/src/ProjectComponents/SetupComponents/index.js
  asreview/webapp/src/ProjectComponents/index.js
  asreview/webapp/src/StyledComponents/StyledButton.js
  asreview/webapp/utils/project.py
Labels: front-end

#956 Adjust project review page when no unlabeled record found
  asreview/webapp/src/App.js
  asreview/webapp/src/PostReviewComponents/ReviewZoneComplete.js
  asreview/webapp/src/PostReviewComponents/index.js
  asreview/webapp/src/ProjectComponents/ProjectPage.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/ReviewPage.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/ReviewPageFinished.js
  asreview/webapp/utils/project.py
Labels: front-end

#951 Add warning about duplicates when uploading dataset
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/AddDataset.js
Labels: Discussion

#962 Unify homepage dashboard and project subpage style
  asreview/webapp/src/App.css
  asreview/webapp/src/HomeComponents/DashboardComponents/DashboardPage.css
  asreview/webapp/src/HomeComponents/DashboardComponents/DashboardPage.js
  asreview/webapp/src/HomeComponents/DashboardComponents/DashboardPageHeader.js
  asreview/webapp/src/HomeComponents/DashboardComponents/NumberCard.js
  asreview/webapp/src/HomeComponents/DashboardComponents/ProjectTable.js
  asreview/webapp/src/HomeComponents/DashboardComponents/index.js
  asreview/webapp/src/HomeComponents/HomePage.js
  asreview/webapp/src/ProjectComponents/AnalyticsComponents/NumberCard.js
  asreview/webapp/src/ProjectComponents/ExportComponents/ExportPage.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/HistoryPage.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecordCard.js
  asreview/webapp/src/ProjectComponents/ProjectPage.js
Labels: front-end

#974 add link to discussion board about when to stop screening
  docs/source/features/post_screening.rst
  docs/source/features/screening.rst
  docs/source/guides/activelearning.rst
  docs/source/lab/oracle.rst
Labels: documentation

#964 remove debug label from documentation
  docs/source/intro/datasets.rst
Labels: documentation

#980 Include PyPi badge in documentation
  README.md
Labels: documentation

#963 Separate FAB buttons for creating and importing a project
  asreview/webapp/src/App.css
  asreview/webapp/src/HomeComponents/DashboardComponents/DashboardPage.js
  asreview/webapp/src/HomeComponents/DashboardComponents/DashboardPageHeader.js
  asreview/webapp/src/HomeComponents/DashboardComponents/ProjectTable.js
  asreview/webapp/src/ProjectComponents/AnalyticsComponents/AnalyticsPage.js
Labels: front-end

#983 Add react router for page routing
  asreview/webapp/api.py
  asreview/webapp/package-lock.json
  asreview/webapp/package.json
  asreview/webapp/src/App.js
  asreview/webapp/src/BootPage.css
  asreview/webapp/src/BootPage.js
  asreview/webapp/src/Components/DrawerItem.js
  asreview/webapp/src/Components/DrawerItemContainer.js
  asreview/webapp/src/Components/Header.js
  asreview/webapp/src/Components/NavigationDrawer.js
  asreview/webapp/src/Components/index.js
  asreview/webapp/src/HomeComponents/DashboardComponents/DashboardPage.js
  asreview/webapp/src/HomeComponents/DashboardComponents/DashboardPageHeader.js
  asreview/webapp/src/HomeComponents/DashboardComponents/ProjectCheckDialog.js
  asreview/webapp/src/HomeComponents/DashboardComponents/ProjectTable.js
  asreview/webapp/src/HomeComponents/HomePage.js
  asreview/webapp/src/ProjectComponents/AnalyticsComponents/AnalyticsPage.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/DataForm.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/DataFormCard.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/DetailsPage.js
  asreview/webapp/src/ProjectComponents/DetailsComponents/ModelForm.js
  asreview/webapp/src/ProjectComponents/ExportComponents/ExportPage.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecord.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecordCard.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/RecordCardNote.js
  asreview/webapp/src/ProjectComponents/ProjectDeleteDialog.js
  asreview/webapp/src/ProjectComponents/ProjectInfoForm.js
  asreview/webapp/src/ProjectComponents/ProjectPage.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/ReviewPage.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/ReviewPageFinished.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/AddDataset.js
  asreview/webapp/src/ProjectComponents/SetupComponents/DataComponents/AddPriorKnowledge.js
  asreview/webapp/src/ProjectComponents/SetupComponents/FinishSetup.js
  asreview/webapp/src/ProjectComponents/SetupComponents/SetupDialog.js
  asreview/webapp/src/ProjectComponents/index.js
  asreview/webapp/src/RouteNotFound.js
  asreview/webapp/src/WelcomeScreen.js
  asreview/webapp/src/api/BaseAPI.js
  asreview/webapp/src/api/ProjectAPI.js
  asreview/webapp/src/constants/action-types.js
  asreview/webapp/src/icons/ElasIcon.js
  asreview/webapp/src/icons/PlusIcon.js
  asreview/webapp/src/icons/index.js
  asreview/webapp/src/images/ElasPotter.png
  asreview/webapp/src/index.js
  asreview/webapp/src/redux/actions/index.js
  asreview/webapp/src/redux/reducers/index.js
  asreview/webapp/tests/test_api.py
  asreview/webapp/tests/test_project.py
Labels: enhancement, front-end

#967 add information about a-synchronic labeling to documentation
  docs/source/lab/oracle.rst
Labels: documentation

#993 Hotfix for issue with RIS exporter (export of nans)
  asreview/io/ris_writer.py
  tests/demo_data/ris_issue_992.txt
  tests/test_writers.py
Labels: bug
