Repository asreview/asreview, pull requests merged in 2024-10, with the labels that each got.

#1864 Fix problems with state handling of SetupDialog
  asreview/webapp/src/HomeComponents/DashboardComponents/DashboardPageHeader.js
  asreview/webapp/src/HomeComponents/DashboardComponents/NewProjectButton.js
  asreview/webapp/src/HomeComponents/DashboardComponents/Projects.js
  asreview/webapp/src/HomeComponents/DashboardComponents/ProjectsOverview.js
  asreview/webapp/src/ProjectComponents/SetupComponents/SetupDialog.js
Labels: bug

#1897 Disable settings in simulate projects
  asreview/webapp/src/ProjectComponents/DetailsComponents/DetailsPage.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabelHistory.js
  asreview/webapp/src/ProjectComponents/SetupComponents/ModelCard.js
  asreview/webapp/src/ProjectComponents/SetupComponents/PriorCard.js
Labels: front-end

#1861 Add queue that manages training of models and simulations
  DEVELOPMENT.md
  asreview/webapp/api/projects.py
  asreview/webapp/app.py
  asreview/webapp/entry_points/lab.py
  asreview/webapp/entry_points/task_manager.py
  asreview/webapp/task_manager/__init__.py
  asreview/webapp/task_manager/models.py
  asreview/webapp/task_manager/task_manager.py
  asreview/webapp/tasks.py
  pyproject.toml
Labels: enhancement, front-end

#1819 Update progress.rst changing ASReview_prior to asreview_prior
  docs/source/lab/progress.rst
Labels: documentation

#1908 Add support for landscape view, tag columns, and add color
  asreview/webapp/src/Components/ProfilePopper.js
  asreview/webapp/src/Components/SettingsDialog.js
  asreview/webapp/src/ProjectComponents/HistoryComponents/LabeledRecord.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/RecordCard.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/RecordCardLabeler.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/ReviewPage.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/TagsTable.js
  asreview/webapp/src/context/ReviewSettingsContext.js
Labels: front-end
