Repository asreview/asreview, pull requests merged in 2024-12, with the labels that each got.

#1954 Add user info for labeled records on collection page
  asreview/webapp/api/projects.py
  asreview/webapp/api/team.py
  asreview/webapp/src/ProjectComponents/ReviewComponents/RecordCard.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/RecordCardLabeler.js
Labels: enhancement

#1956 Replace UTC time with unix time in state and project files
  asreview/migrate.py
  asreview/project/api.py
  asreview/project/schema.py
  asreview/simulation/simulate.py
  asreview/state/sqlstate.py
  asreview/webapp/api/projects.py
  asreview/webapp/entry_points/auth_tool.py
  asreview/webapp/src/HomeComponents/DashboardComponents/ProjectCard.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/RecordCard.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/RecordCardLabeler.js
  asreview/webapp/tests/test_extensions/test_auth_tool.py
  tests/asreview_files/test_state_example_converted.asreview/reviews/e2cb5cb86ce44a10b9f9dd59510830d4/results.db
  tests/asreview_files/test_state_example_with_times.asreview/data/cohen_no_labels.csv
  tests/asreview_files/test_state_example_with_times.asreview/data/cohen_no_labels.csv.pickle
  tests/asreview_files/test_state_example_with_times.asreview/feature_matrices/tfidf_feature_matrix.npz
  tests/asreview_files/test_state_example_with_times.asreview/legacy/data/cohen_no_labels.csv
  tests/asreview_files/test_state_example_with_times.asreview/legacy/data/cohen_no_labels.csv.pickle
  tests/asreview_files/test_state_example_with_times.asreview/legacy/labeled.json
  tests/asreview_files/test_state_example_with_times.asreview/legacy/lock.sqlite
  tests/asreview_files/test_state_example_with_times.asreview/legacy/pool.json
  tests/asreview_files/test_state_example_with_times.asreview/legacy/project.json
  tests/asreview_files/test_state_example_with_times.asreview/lock.sqlite
  tests/asreview_files/test_state_example_with_times.asreview/project.json
  tests/asreview_files/test_state_example_with_times.asreview/project.json.lock
  tests/asreview_files/test_state_example_with_times.asreview/reviews/7dbe54958ef4443a8a0df5c387fa4700/results.db
  tests/asreview_files/test_state_example_with_times.asreview/reviews/7dbe54958ef4443a8a0df5c387fa4700/settings_metadata.json
  tests/test_init.py
  tests/test_state.py
Labels: bug, enhancement

#1949 Fix loader animation in reviewer screen
  asreview/state/sqlstate.py
  asreview/webapp/src/ProjectComponents/ReviewComponents/RecordCardLabeler.js
Labels: bug

#1959 Add option to export reviewer information on dataset export
  asreview/webapp/api/projects.py
  asreview/webapp/src/ProjectComponents/HistoryComponents/ExportDialog.js
  asreview/webapp/src/api/ProjectAPI.js
Labels: enhancement

#1967 Fix numpy empty array bool check
  asreview/data/ris.py
Labels: bug

#1973 Add informative error message when extension name not found
  asreview/extensions.py
Labels: enhancement

#1974 Update cli.py format algorithm with extension detection
  asreview/models/cli.py
Labels: enhancement

#1972 Replace balance strategies by sample weight
  asreview/models/balance/__init__.py
  asreview/models/balance/balanced.py
  asreview/models/balance/base.py
  asreview/models/balance/double.py
  asreview/models/balance/undersample.py
  asreview/models/classifiers/base.py
  asreview/models/default.py
  asreview/simulation/cli.py
  asreview/simulation/simulate.py
  asreview/webapp/api/projects.py
  asreview/webapp/tasks.py
  asreview/webapp/tests/integration_tests/signup_signin_create_project_test.py
  asreview/webapp/tests/utils/misc.py
  pyproject.toml
  tests/test_balance.py
  tests/test_models.sh
  tests/test_simulate.py
  tests/test_simulate_cli.py
  tests/test_state.py
Labels: enhancement, extensions

#1986 Remove classifier class_weights and small changes
  asreview/models/classifiers/logistic.py
  asreview/models/classifiers/nb.py
  asreview/models/classifiers/rf.py
  asreview/models/classifiers/svm.py
  asreview/models/classifiers/utils.py
Labels: models

#1991 Fix don't publish Docker prereleases
  .github/workflows/docker.yml
Labels: bug

#1993 Fix dataset PRAGMA error on non SQLite webapp database
  asreview/__init__.py
  asreview/data/store.py
Labels: bug
