Repository asreview/asreview, pull requests merged in 2024-01, with the labels that each got.

#1621 Add read_data method to ASReviewProject
  asreview/entry_points/simulate.py
  asreview/exceptions.py
  asreview/project.py
  asreview/webapp/api/projects.py
  asreview/webapp/entry_points/run_model.py
  asreview/webapp/io.py
Labels: enhancement

#1639 Improve documentation on new exported columns
  docs/source/progress.rst
Labels: documentation

#1527 Add custom review tags
  .gitignore
  asreview/_version.py
  asreview/config.py
  asreview/project.py
  asreview/state/compatibility.py
  asreview/state/custom_metadata_mapper.py
  asreview/state/sqlstate.py
  asreview/webapp/api/projects.py
  asreview/webapp/src/ProjectComponents/DetailsComponents/DetailsPage.js
  asreview/webapp/src/ProjectComponents/ProjectPage.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/ReviewPage.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/TagsTable.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/index.js
  asreview/webapp/src/ProjectComponents/SetupComponents/ScreenComponents/ScreenLanding.js
  asreview/webapp/src/ProjectComponents/SetupComponents/ScreenComponents/index.js
  asreview/webapp/src/ProjectComponents/SetupComponents/SetupDialog.js
  asreview/webapp/src/ProjectComponents/SetupComponents/SetupStepper.js
  asreview/webapp/src/ProjectComponents/TagComponents/TagEditor.js
  asreview/webapp/src/ProjectComponents/TagComponents/index.js
  asreview/webapp/src/api/ProjectAPI.js
  asreview/webapp/tests/test_api/test_projects.py
  asreview/webapp/tests/utils/api_utils.py
  tests/asreview_files/test_state_example_converted.asreview/reviews/e2cb5cb86ce44a10b9f9dd59510830d4/results.sql
  tests/asreview_files/test_state_example_converted.asreview/reviews/e2cb5cb86ce44a10b9f9dd59510830d4/settings_metadata.json
  tests/asreview_files/test_state_example_with_times.asreview/reviews/7dbe54958ef4443a8a0df5c387fa4700/results.sql
  tests/asreview_files/test_state_example_with_times.asreview/reviews/7dbe54958ef4443a8a0df5c387fa4700/settings_metadata.json
  versioneer.py
Labels: enhancement, front-end

#1629 Improve documentation on extensions
  docs/source/cli.rst
  docs/source/conf.py
  docs/source/extensions_dev.rst
  docs/source/index.rst
  docs/source/overview_development.rst
  docs/source/products.rst
  docs/source/project_create.rst
  docs/source/simulation_cli.rst
Labels: documentation
