Repository asreview/asreview, pull requests merged in 2025-05, with the labels that each got.

#2201 Fix update decisions data table and rename column
  asreview/project/migrate.py
  asreview/simulation/simulate.py
  asreview/state/sqlstate.py
  asreview/webapp/_api/projects.py
  asreview/webapp/src/ProjectComponents/ReviewComponents/RecordCardLabeler.js
  asreview/webapp/src/api/ProjectAPI.js
  tests/asreview_files/asreview-demo-project-invalid-classifier.asreview
  tests/asreview_files/asreview-demo-project.asreview
  tests/test_state.py
Labels: bug

#2203 Remove ASReview extensions from Dockerfile to avoid circular build
  Dockerfile
Labels: Docker

#2204 Delete .github/workflows/docs.yml in favor of ReadTheDocs builds
  .github/workflows/docs.yml
  .readthedocs.yaml
Labels: documentation

#2202 Update README for version 2 release
  README.md
  images/ASReviewWebApp.png
Labels: documentation

#2211 Fix migration for datasets with empty columns
  asreview/data/base.py
  tests/test_data_store.py
Labels: bug

#2223 Bump scikit-learn version to 1.5
  pyproject.toml
Labels: bug, dependencies
