Repository asreview/asreview, pull requests merged in 2025-02, with the labels that each got.

#2046 Fix Flask-Login version to 1.6.3 due to removal of LOGIN_DISABLED
  setup.py
Labels: dependencies

#2045 Fix Flask-Login version to 1.6.3 due to removal of LOGIN_DISABLED
  setup.py
Labels: dependencies

#2054 Fix display of add team member in header without authentication
  asreview/webapp/src/Components/Header.js
Labels: bug

#2071 Add extra pages to ReviewPage for finished and empty pool
  asreview/webapp/_api/projects.py
  asreview/webapp/src/ProjectComponents/ReviewComponents/ReviewPage.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/ReviewPageFinished.js
  asreview/webapp/src/ProjectComponents/ReviewComponents/index.js
  asreview/webapp/tests/test_api/test_projects.py
Labels: enhancement

#2066 Sign in a user after successful account creation or password reset
  asreview/webapp/_api/auth.py
  asreview/webapp/src/Components/ConfirmAccount.js
  asreview/webapp/src/Components/ResetPassword.js
  asreview/webapp/src/api/AuthAPI.js
  asreview/webapp/tests/test_api/test_auth.py
Labels: enhancement

#2051 Rename navrail items (customize, settings)
  asreview/webapp/src/App.js
  asreview/webapp/src/Components/PageWithDrawer.js
  asreview/webapp/src/Components/ProjectDrawerItems.js
Labels: front-end

#2041 Add models with parameters for V2 version
  asreview/models/classifiers.py
  asreview/models/feature_extractors.py
  asreview/models/models.py
  asreview/webapp/tests/utils/misc.py
  tests/test_simulate.py
  tests/test_simulate_cli.py
Labels: enhancement, front-end
